#!/usr/bin/env bash
# Deploy this working tree to the directory the ZENITH daemon actually runs from.
#
#   ./deploy.sh                  sync + verify + restart
#   ./deploy.sh --no-restart     sync + verify only (enough for frontend-only changes)
#   ./deploy.sh --dry-run        show what would change, touch nothing
#   ZENITH_HOME=/path ./deploy.sh
#
# WHY THIS EXISTS. The daemon does not run from the repo. On macOS,
# /Library/LaunchDaemons/com.zenith.os.plist runs $ZENITH_HOME/launch-zenith.sh with
# KeepAlive=true, and $ZENITH_HOME is a PLAIN DIRECTORY — not a checkout. `git pull`
# cannot reach it, so committing alone changes nothing about what is running, and the
# two silently drift (an endpoint 404s while the code for it sits in git).
#
# This is the DEV-BOX path only. A normal install from get.sh clones into ~/.zenith,
# which IS a checkout, and updates with `zenith update` (git pull + restart).
#
# Safety: the deployed copy is compiled and self-checked BEFORE the server is
# restarted, and server.py is restored from its backup if either fails — a bad deploy
# should never take the daemon down, because KeepAlive would then respawn it into a
# crash loop.
set -euo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)"
DEST="${ZENITH_HOME:-$HOME/zenith-src}"
PORT="${ZENITH_PORT:-8777}"
PY="${ZENITH_PYTHON:-/usr/bin/python3}"
command -v "$PY" >/dev/null 2>&1 || PY=python3

RESTART=1; DRYRUN=0
for a in "$@"; do
  case "$a" in
    --no-restart) RESTART=0 ;;
    --dry-run)    DRYRUN=1 ;;
    -h|--help)    sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown flag: $a (try --help)" >&2; exit 2 ;;
  esac
done

# Runtime payload only. data/ is deliberately absent: it holds config.json,
# gpu_nodes.json, deploy.env and the event store — machine state the repo must
# never overwrite.
FILES=(server.py zenith_agents.py zenith_store.py launch-zenith.sh VERSION)
DIRS=(static scripts defaults bin)

c(){ printf '\033[%sm%s\033[0m' "$1" "$2"; }
ok(){   printf '  %s %s\n' "$(c 32 '✓')" "$*"; }
warn(){ printf '  %s %s\n' "$(c 33 '!')" "$*"; }
die(){  printf '  %s %s\n' "$(c 31 '✗')" "$*" >&2; exit 1; }
step(){ printf '\n%s\n' "$(c '36;1' "▸ $*")"; }

[ "$SRC" != "$DEST" ] || die "ZENITH_HOME is the repo itself — nothing to deploy"
[ -d "$DEST" ] || die "no such directory: $DEST (set ZENITH_HOME)"
[ -f "$DEST/server.py" ] || die "$DEST does not look like a ZENITH install (no server.py)"

# --- what would change -------------------------------------------------------
step "changes"
CHANGED=()
for f in "${FILES[@]}"; do
  [ -f "$SRC/$f" ] || continue
  cmp -s "$SRC/$f" "$DEST/$f" || CHANGED+=("$f")
done
for d in "${DIRS[@]}"; do
  [ -d "$SRC/$d" ] || continue
  while IFS= read -r f; do
    rel="${f#"$SRC"/}"
    [ "$rel" = "scripts/statusline.py" ] && continue      # generated; see the copy loop
    cmp -s "$f" "$DEST/$rel" 2>/dev/null || CHANGED+=("$rel")
  done < <(find "$SRC/$d" -type f ! -name '*.pyc' ! -name '.DS_Store')
done
if [ ${#CHANGED[@]} -eq 0 ]; then
  ok "already in sync — nothing to copy"
  [ "$RESTART" = 1 ] || exit 0
else
  for f in "${CHANGED[@]}"; do printf '    %s\n' "$f"; done
  ok "${#CHANGED[@]} file(s) to deploy"
fi
# Deploying uncommitted work is normal (that IS how you test it), but on a box where
# several agent sessions share the checkout it is easy to ship someone ELSE's
# half-finished edit to the live daemon. So: name what is uncommitted, don't block.
if git -C "$SRC" rev-parse --git-dir >/dev/null 2>&1; then
  DIRTY="$(git -C "$SRC" status --porcelain -- "${FILES[@]}" "${DIRS[@]}" 2>/dev/null || true)"
  if [ -n "$DIRTY" ]; then
    warn "deploying UNCOMMITTED changes:"
    printf '%s\n' "$DIRTY" | sed 's/^/      /'
    warn "if any of that is not yours, commit or stash before deploying"
  fi
fi

[ "$DRYRUN" = 0 ] || { warn "dry run — stopping here"; exit 0; }

# --- verify the SOURCE first, so a typo never reaches the daemon -------------
step "verify source"
"$PY" -m py_compile "$SRC/server.py" || die "server.py does not compile — fix before deploying"
ok "compiles"

# --- copy --------------------------------------------------------------------
step "deploy → $DEST"
STAMP="$(date +%Y%m%d-%H%M%S)"
BAK="$DEST/server.py.bak-$STAMP-predeploy"
cp -p "$DEST/server.py" "$BAK"
ok "backup → $(basename "$BAK")"
for f in "${FILES[@]}"; do
  [ -f "$SRC/$f" ] && cp -p "$SRC/$f" "$DEST/$f"
done
for d in "${DIRS[@]}"; do
  [ -d "$SRC/$d" ] || continue
  mkdir -p "$DEST/$d"
  while IFS= read -r f; do
    rel="${f#"$SRC"/}"
    # scripts/statusline.py is GENERATED by the server from STATUSLINE_SCRIPT_SRC and is
    # gitignored for that reason. Copying it pushes whatever stale copy sits in the working
    # tree OVER the fresh one the server just wrote — which is how a months-old statusline
    # survived several restarts and silently dropped every transcript-derived widget.
    [ "$rel" = "scripts/statusline.py" ] && continue
    mkdir -p "$DEST/$(dirname "$rel")"
    cp -p "$f" "$DEST/$rel"
  done < <(find "$SRC/$d" -type f ! -name '*.pyc' ! -name '.DS_Store')
done
ok "copied"

# --- verify the DEPLOYED copy, roll back if it is broken ---------------------
step "verify deployed copy"
if ! ( cd "$DEST" && "$PY" -m py_compile server.py && "$PY" server.py check ); then
  cp -p "$BAK" "$DEST/server.py"
  die "deployed server.py failed its checks — server.py rolled back from $(basename "$BAK")
     (static assets were still copied; re-run once the Python side is fixed)"
fi
ok "compiles + self-check passes"

[ "$RESTART" = 1 ] || { step "done"; ok "not restarting (--no-restart) — reload the browser for frontend changes"; exit 0; }

# --- restart -----------------------------------------------------------------
# macOS: the LaunchDaemon has KeepAlive=true, so killing it IS the restart.
# Linux: prefer the systemd user unit if one is installed.
step "restart"
if command -v systemctl >/dev/null 2>&1 && systemctl --user status zenith >/dev/null 2>&1; then
  systemctl --user restart zenith && ok "systemctl --user restart zenith"
else
  PIDS="$(pgrep -f "$DEST/server.py" || true)"
  if [ -n "$PIDS" ]; then
    # shellcheck disable=SC2086
    kill $PIDS && ok "signalled $PIDS (KeepAlive respawns it)"
  else
    warn "server was not running — start it with: launchctl kickstart -k system/com.zenith.os"
  fi
fi

step "health"
for i in $(seq 1 40); do
  if "$PY" - "$PORT" <<'PYEOF' 2>/dev/null
import sys, urllib.request
urllib.request.urlopen("http://127.0.0.1:%s/api/overview" % sys.argv[1], timeout=3).read()
PYEOF
  then
    ok "responding on :$PORT after ${i}s"
    printf '\n  %s  http://127.0.0.1:%s   %s\n\n' "$(c '32;1' 'ready.')" "$PORT" \
      "$(c 33 '(hard-reload the browser to pick up frontend changes)')"
    exit 0
  fi
  sleep 1
done
die "server did not answer on :$PORT within 40s — check /Users/\$USER/zenith.log"
