#!/usr/bin/env bash
# ZENITH/OS installer — sets up a `zenith` command so you can start + open the
# app with one word. Works on macOS, Linux, and WSL (Ubuntu). Idempotent.
set -euo pipefail

ZENITH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/zenith"

c() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
say() { printf '%s\n' "$*"; }
ok()  { say "  $(c '32' '✓') $*"; }
warn(){ say "  $(c '33' '!') $*"; }
bad() { say "  $(c '31' '✗') $*"; }

say ""
say "$(c '36;1' '  ZENITH/OS')  installer"
say "  $ZENITH_DIR"
say ""

# --- detect platform ---
IS_WSL=0
grep -qi microsoft /proc/version 2>/dev/null && IS_WSL=1
case "$(uname -s)" in
  Darwin) PLATFORM="macOS" ;;
  Linux)  PLATFORM=$([ "$IS_WSL" = 1 ] && echo "WSL" || echo "Linux") ;;
  *)      PLATFORM="$(uname -s)" ;;
esac
say "  platform: $(c '36' "$PLATFORM")"
say ""

# --- requirements ---
say "  checking requirements…"
MISSING=0
if command -v python3 >/dev/null 2>&1; then
  ok "python3 — $(python3 --version 2>&1)"
else
  bad "python3 not found (required)"
  [ "$PLATFORM" = "macOS" ] && warn "install: brew install python3" \
    || warn "install: sudo apt update && sudo apt install -y python3"
  MISSING=1
fi
if command -v tmux >/dev/null 2>&1; then
  ok "tmux — persistent terminals (sessions survive restarts)"
else
  # Not a nicety: without tmux every terminal is a child of the server process, so
  # any restart silently destroys every open session. Offer to fix it right here
  # rather than printing advice that scrolls past and never gets acted on.
  bad "tmux not found — WITHOUT IT, RESTARTING ZENITH KILLS EVERY OPEN TERMINAL"
  warn "  (terminals become children of the server process; agent sessions die with it)"
  if [ "$PLATFORM" = "macOS" ] && command -v brew >/dev/null 2>&1; then
    TMUX_CMD="brew install tmux"
  elif command -v apt-get >/dev/null 2>&1; then
    TMUX_CMD="sudo apt-get install -y tmux"
  elif command -v dnf >/dev/null 2>&1; then
    TMUX_CMD="sudo dnf install -y tmux"
  elif command -v pacman >/dev/null 2>&1; then
    TMUX_CMD="sudo pacman -S --noconfirm tmux"
  else
    TMUX_CMD=""
  fi
  if [ -z "$TMUX_CMD" ]; then
    warn "  no supported package manager found — install tmux yourself, then re-run"
  elif [ -t 0 ]; then
    printf "  install it now? [%s] (Y/n) " "$TMUX_CMD"
    read -r REPLY </dev/tty || REPLY=n
    case "$REPLY" in
      ''|[Yy]*) say "  installing tmux…"
                if $TMUX_CMD; then ok "tmux installed"; else bad "tmux install failed — run: $TMUX_CMD"; fi ;;
      *)        warn "  skipped — install later with: $TMUX_CMD" ;;
    esac
  else
    warn "  non-interactive shell — install it with: $TMUX_CMD"
  fi
fi
if command -v claude >/dev/null 2>&1; then
  ok "claude CLI — $(claude --version 2>&1 | head -1)"
else
  warn "claude CLI not found — needed to open Claude sessions"
  warn "  get it working in this shell first: https://claude.com/claude-code"
fi
[ "$MISSING" = 1 ] && { say ""; bad "install the required tools above, then re-run ./install.sh"; exit 1; }
say ""

# --- write the launcher ---
mkdir -p "$BIN_DIR" "$ZENITH_DIR/data/logs"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# ZENITH/OS launcher (generated by install.sh)
ZENITH_DIR="$ZENITH_DIR"
LAUNCHER_EOF
cat >> "$LAUNCHER" <<'LAUNCHER_EOF'
PORT="${ZENITH_PORT:-8777}"
URL="http://localhost:$PORT"
PIDFILE="$ZENITH_DIR/data/zenith.pid"
LOG="$ZENITH_DIR/data/logs/zenith.log"

running() { python3 -c "import urllib.request; urllib.request.urlopen('$URL/api/overview', timeout=2)" >/dev/null 2>&1; }
_svc() { case "$(uname -s)" in Darwin) echo launchd ;; *) echo systemd ;; esac; }   # OS → supervisor

open_url() {
  if grep -qi microsoft /proc/version 2>/dev/null; then          # WSL → Windows browser
    command -v wslview >/dev/null 2>&1 && { wslview "$URL"; return; }
    command -v explorer.exe >/dev/null 2>&1 && { explorer.exe "$URL" >/dev/null 2>&1 || true; return; }
  fi
  case "$(uname -s)" in
    Darwin) open "$URL" ;;
    *) command -v xdg-open >/dev/null 2>&1 && xdg-open "$URL" >/dev/null 2>&1 || true ;;
  esac
}

start() {
  if running; then echo "ZENITH already running → $URL";
  else
    ( cd "$ZENITH_DIR" && ZENITH_PORT="$PORT" nohup python3 server.py >"$LOG" 2>&1 & echo $! >"$PIDFILE" )
    printf "starting ZENITH"
    for _ in $(seq 1 30); do running && break; printf .; sleep 0.4; done; echo
    running || { echo "failed to start — see $LOG"; return 1; }
    echo "ZENITH online → $URL"
  fi
  open_url
}
stop() {
  [ -f "$PIDFILE" ] && kill "$(cat "$PIDFILE")" 2>/dev/null && rm -f "$PIDFILE" && echo "stopped" || echo "not running"
}
case "${1:-start}" in
  start|open|"") start ;;
  stop)   stop ;;
  restart) stop; sleep 1; start ;;
  status) running && echo "running → $URL" || echo "stopped" ;;
  update) ( cd "$ZENITH_DIR" && git pull ) && { stop; sleep 1; start; } ;;
  logs)   tail -f "$LOG" ;;
  autostart)     bash "$ZENITH_DIR/scripts/install-$(_svc).sh" ;;      # keep running + survive reboot
  autostart-off) bash "$ZENITH_DIR/scripts/uninstall-$(_svc).sh" ;;
  *) echo "usage: zenith [start|stop|restart|status|update|logs|autostart|autostart-off]" ;;
esac
LAUNCHER_EOF
chmod +x "$LAUNCHER"
chmod +x "$ZENITH_DIR"/scripts/*.sh 2>/dev/null || true
ok "installed launcher → $LAUNCHER"

# --- ensure ~/.local/bin is on PATH ---
ON_PATH=0
case ":$PATH:" in *":$BIN_DIR:"*) ON_PATH=1 ;; esac
if [ "$ON_PATH" = 0 ]; then
  RC="$HOME/.bashrc"; [ -n "${ZSH_VERSION:-}" ] || [ "$(basename "${SHELL:-}")" = "zsh" ] && RC="$HOME/.zshrc"
  LINE='export PATH="$HOME/.local/bin:$PATH"'
  grep -qF "$LINE" "$RC" 2>/dev/null || printf '\n# ZENITH/OS\n%s\n' "$LINE" >> "$RC"
  warn "added ~/.local/bin to PATH in $RC — run:  source $RC   (or open a new terminal)"
fi

# --- auto-start service: keep ZENITH running + bring it back after a reboot ---
# Opt out with:  ZENITH_NO_AUTOSTART=1 ./install.sh
AUTOSTART_ON=0
if [ "${ZENITH_NO_AUTOSTART:-0}" != 1 ]; then
  say ""
  say "  enabling auto-start (keeps ZENITH running, restarts after reboot)…"
  case "$PLATFORM" in
    macOS)
      bash "$ZENITH_DIR/scripts/install-launchd.sh" >/dev/null 2>&1 \
        && { ok "auto-start on (launchd)"; AUTOSTART_ON=1; } || warn "auto-start setup failed — run 'zenith' manually" ;;
    Linux)
      if command -v systemctl >/dev/null 2>&1; then
        bash "$ZENITH_DIR/scripts/install-systemd.sh" >/dev/null 2>&1 \
          && { ok "auto-start on (systemd)"; AUTOSTART_ON=1; } || warn "auto-start setup failed — run 'zenith' manually"
      else warn "systemd not found — auto-start skipped; run 'zenith' to start"; fi ;;
    WSL)  warn "WSL: auto-start needs systemd ('systemd=true' in /etc/wsl.conf); skipped — run 'zenith'" ;;
    *)    warn "auto-start not supported on $PLATFORM yet — run 'zenith' to start" ;;
  esac
  [ "$AUTOSTART_ON" = 1 ] && warn "turn it off any time with:  zenith autostart-off"
fi

say ""
if [ "$AUTOSTART_ON" = 1 ]; then
  say "  $(c '32;1' 'done.')  ZENITH is running + will auto-start on boot. open it with:"
else
  say "  $(c '32;1' 'done.')  start ZENITH with:"
fi
say ""
say "      $(c '36;1' 'zenith')            $(c '90' '# start the server + open in your browser')"
say ""
say "  other commands:  zenith stop | restart | status | update | logs"
[ "$ON_PATH" = 0 ] && say "  (if 'zenith' isn't found yet, run:  $(c '36' "$LAUNCHER")  or reopen your terminal)"
say ""
